name: Update Connector SA Key

on:
  workflow_dispatch:

jobs:
  deploy-connector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Connector
        run: |
          curl -u "${{ secrets.CC_API_KEY }}:${{ secrets.CC_API_SECRET }}" \
            -X PUT \
            -H "Content-Type: application/json" \
            --data @deploy_connector.json \
            "https://api.confluent.cloud/connect/v1/environments/env-q5r2r2/clusters/lkc-qvvy9m/connectors/MongoDbAtlasSinkConnector_0/config"
