name: Deploy MongoDB Sink Connector

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CC_API_KEY: ${{ secrets.CC_API_KEY }}
      CC_API_SECRET: ${{ secrets.CC_API_SECRET }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      NEW_SERVICE_ACCOUNT_ID: ${{ secrets.SERVICE_ACCOUNT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Replace variables using envsubst
        run: |
          envsubst < deploy_connector_template.json > deploy_connector.json

      - name: Deploy connector
        run: |
          curl -u "$CC_API_KEY:$CC_API_SECRET" \
            -X PUT \
            -H "Content-Type: application/json" \
            --data @deploy_connector.json \
            "https://api.confluent.cloud/connect/v1/environments/env-q5r2r2/clusters/lkc-qvvy9m/connectors/MongoDbAtlasSinkConnector_0/config"
